# Generated by Django 5.0.1 on 2025-02-08 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patent_number', models.CharField(max_length=100)),
                ('patent_title', models.CharField(max_length=200)),
                ('inventor_name', models.CharField(max_length=100)),
                ('filing_date', models.DateField()),
                ('patent_status', models.CharField(max_length=20)),
            ],
        ),
    ]
