# Generated by Django 5.0.1 on 2025-02-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_patent_bed_allotted_patent_bed_number_patent_icu_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patent',
            name='patent_age',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
    ]
