# Generated by Django 5.0.1 on 2025-02-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0003_patent_patent_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='patent',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='patient_photos/'),
        ),
    ]
