# Generated by Django 5.0.1 on 2025-02-08 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0004_patent_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='patent',
            name='address',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patent',
            name='billing_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
