# Generated by Django 5.0.1 on 2025-02-08 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_patent_address_patent_billing_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patent',
            name='patent_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
