# Generated by Django 5.0.1 on 2025-02-08 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_alter_patent_patent_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='patent',
            name='patent_gender',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patent',
            name='address',
            field=models.CharField(max_length=200),
        ),
    ]
