# Generated by Django 5.0.1 on 2025-02-08 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_patent_patent_gender_alter_patent_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.CharField(max_length=100, unique=True)),
                ('doctor_photo', models.ImageField(blank=True, null=True, upload_to='doctor_photos/')),
                ('doctor_sign_photo', models.ImageField(blank=True, null=True, upload_to='doctor_photos/')),
                ('doctor_status', models.CharField(max_length=20)),
                ('doctor_age', models.CharField(max_length=20)),
                ('doctor_gender', models.CharField(max_length=20)),
                ('doctor_title', models.CharField(max_length=200)),
                ('doctor_number', models.CharField(max_length=100)),
                ('doctor_designation', models.CharField(max_length=100)),
            ],
        ),
    ]
