# Generated by Django 5.0.1 on 2025-02-08 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0008_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='patent',
            name='patent_doctor',
            field=models.CharField(default='ABC', max_length=20),
            preserve_default=False,
        ),
    ]
