# Generated by Django 5.0.1 on 2025-02-08 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_patent_patent_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='doctor_title',
            new_name='doctor_name',
        ),
        migrations.AddField(
            model_name='patent',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Main.doctor'),
        ),
    ]
