# Generated by Django 5.0.1 on 2025-02-08 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0011_blood_medicine_organ'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='medicine_donars',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
