# Generated by Django 5.0.1 on 2025-02-08 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0012_medicine_medicine_donars'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicine',
            old_name='medicine_donars',
            new_name='medicine_category',
        ),
    ]
